spring.application.name=foodapp
spring.datasource.url=jdbc:mysql://localhost:3306/foodapp
spring.datasource.username=root
spring.datasource.password=Shelly@15
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true









